Updateable Chip Span (allows for asynchronously loading images from urls/libraries)
hootsuite/nachos pull request #39
Opened 2017-10-19 01:40 UTC by bagintz

### Summary
This PR has a new ChipSpan clone... UpdateableChipSpan which swaps out the Drawable Icon for a StateListDrawable.  This StateListDrawable is initiated with the placeholder image (which is effectively the same as ChipSpan.  Out of the box it will act the same as ChipSpan.  

The difference is that you can use Picasso, Glide, Fresco or any other libraries that asynchronously return a drawable to update the Chip/ImageSpan by calling the new `UpdateableChipSpan#changeIcon(Drawable newIcon)` method.  You must call NachoTextView#invalidateChips() on your NachoTextView for it to properly update the view.

It seems to work seamlessly with no side effects.  I am sure there are more elegant ways to implement this, but it seemed the least invasive at the time.

*I noticed that the NachoTextView#init(AttributeSet attrs) defaults to the ChipSpan class, so I am not sure if there needs to be another method added there for this one????

### Test Plan

Was going to duplicate the ChipSpanChipCreatorTest, but was unable to get it to pass locally so I am willing to write tests if I can get some direction/help with that

2017-10-19 01:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hootsuite/nachos?pullRequest=39) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/hootsuite/nachos?pullRequest=39) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Bryan Gintz<br/>:x: bagintz<br/><hr/>**Bryan Gintz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hootsuite/nachos?pullRequest=39) it.</sub>

2017-10-19 02:00 UTC, bagintz commented
I had a git email screwup and some of the commits are from an unassociated account.  I can resubmit a new PR if needed from the correct user (bagintz)

2017-10-19 10:00 UTC, miroslavign commented
@bagintz tnx for the pointer, I will check this today

2017-10-28 17:42 UTC, bagintz commented
@simon-tse-hs Is the lack of CLA (because of using the wrong email on my end) prevent you from even looking at this?  If so, I can resubmit.

2017-10-30 17:09 UTC, simon-tse-hs requested changes
@bagintz thanks for the PR. I read through the entire thing. I noticed the biggest change is:
- Inclusion of the StateListDrawable (which is just a drawable)
- Adding new attributes for the view

I'll make more comments in the actual code.

2017-10-30 17:09 UTC, simon-tse-hs commented on nachos/src/main/java/com/hootsuite/nachos/chip/UpdateableChipSpan.java
> +    private StateListDrawable mIcon;
⚠️  `StateListDrawable` is just a subclass of `Drawable`. Why couldn't you achieve this change by keeping this a `Drawable`?

2017-10-30 17:09 UTC, simon-tse-hs commented on nachos/src/main/java/com/hootsuite/nachos/chip/UpdateableChipSpan.java
> +    public UpdateableChipSpan(@NonNull Context context, @NonNull CharSequence text, @Nullable StateListDrawable icon, Object data) {
❓  This constructor is the essentially the same as the original one (just below this constructor). What are benefits are you getting by creating this new constructor? Can they be merged?

2017-10-30 17:09 UTC, simon-tse-hs commented
@bagintz if the constructors can be merged, then I argue that your small change could be made into the original `ChipSpan`

2017-11-22 21:03 UTC, bagintz commented
@simon-tse-hs see my responses to your comments

2025-07-02 16:57 UTC, matthew-shin-hs commented
Closing with inactive status. @bagintz apologies as this repository is not actively monitored or maintained and the original authors of the repo are no longer with the company. I am releasing v2.0.0 to migrate the library to AndroidX and so if your changes are still relevant please put up a new PR.

2025-07-02 16:57 UTC, closed without merging